# fly.toml app configuration file generated for staging-dt-27-6-2-1719487372-client on 2024-06-27T11:23:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'staging-dt-27-6-2-1719487372-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
